export const LOGIN_PATH = '/LogIn'
export const SIGNIN_PATH = '/SignIn'
export const USER_HOME_PAGE = './Slots-booking/UserHomePage'
export const ADMIN_HOME_PAGE = '/Slots-booking/AdminHomePage'
export const PREVIOUS_SLOTS_PAGE = './Slots-booking/previous-slots'
export const REPORT_ISSUE = './Slots-booking/report-issues'
